In [9]:
import pandas as pd
import json
import sqlite3

# Data prep

In [10]:
agents_df = pd.read_json("/Users/mukundanramesh/projects/guvi-python-sql-pandas-project-1/datasets/agents_cleaned.json")
agents_df.rename(columns={
    "Agent_ID":"agentid",
    "Name":"name",
    "Phone":"phone",
    "Email":"email",
    "commission_rate":"commissionrate",
    "deals_closed":"dealsclosed",
    "rating":"rating",
    "experience_years":"experienceyears",
    "avg_closing_days":"avgclosingdays"
}, inplace=True)
agents_df.head()

,agentid,name,phone,email,commissionrate,dealsclosed,rating,experienceyears,avgclosingdays
0,A0001,Agent A0001,+1-534-665-8373,a0001@realestate.com,2.00,52,4.3,10,64
1,A0002,Agent A0002,+1-493-463-4698,a0002@realestate.com,2.20,26,3.8,20,82
2,A0003,Agent A0003,+1-290-534-1121,a0003@realestate.com,2.85,297,3.6,21,83
3,A0004,Agent A0004,+1-691-610-4878,a0004@realestate.com,1.67,31,4.5,5,61
4,A0005,Agent A0005,+1-829-613-5411,a0005@realestate.com,1.11,198,4.3,16,67

In [11]:
buyers_df = pd.read_json("/Users/mukundanramesh/projects/guvi-python-sql-pandas-project-1/datasets/buyers_cleaned.json")
buyers_df.rename(columns={
    "buyer_id":"buyerid",
    "sale_id":"saleid",
    "buyer_type":"buyertype",
    "payment_mode":"paymentmode",
    "loan_taken":"loantaken",
    "loan_provider":"loanprovider",
    "loan_amount":"loanamount"
}, inplace=True)
buyers_df.head()

,buyerid,saleid,buyertype,paymentmode,loantaken,loanprovider,loanamount
0,1,L01179,End User,Cash,False,None,0
1,2,L00866,Investor,Cheque,False,None,0
2,3,L00102,Investor,Cheque,True,Axis,2317757
3,4,L00440,Investor,Bank Transfer,False,None,0
4,5,L00059,Investor,UPI,True,HDFC,4191221

In [3]:
listings_df = pd.read_json("/Users/mukundanramesh/projects/guvi-python-sql-pandas-project-1/datasets/listings_final_expanded.json")
listings_df.rename(columns={
    "Listing_ID":"listingid",
    "City":"city",
    "Property_Type":"propertytype",
    "Price":"price",
    "Sqft":"sqft",
    "Date_Listed":"datelisted",
    "Agent_ID":"agentid",
    "Latitude":"latitude",
    "Longitude":"longitude"
}, inplace=True)
listings_df.head()

,listingid,city,propertytype,price,sqft,datelisted,agentid,latitude,longitude
0,L00001,New York,Apartment,1.655144e+06,2753.009121,2023-05-06,A0015,33.965208,-69.861589
1,L00002,Los Angeles,Apartment,1.519141e+06,4966.988193,2023-02-14,A0038,42.547892,-90.277860
2,L00003,Houston,Apartment,1.624890e+05,1267.003959,2023-04-22,A0015,28.732327,-115.952982
3,L00004,Phoenix,Apartment,1.277016e+06,2128.014429,2024-01-02,A0042,26.403938,-74.771490
4,L00005,Phoenix,Townhouse,5.622970e+05,4178.997421,2023-10-29,A0018,39.425252,-83.917878

In [12]:
sales_df = pd.read_csv("/Users/mukundanramesh/projects/guvi-python-sql-pandas-project-1/datasets/sales_cleaned.csv")
sales_df.rename(columns={
    "Listing_ID":"listingid",
    "Sale_Price":"saleprice",
    "Date_Sold":"datesold",
    "Days_on_Market":"daysonmarket"
}, inplace=True)
sales_df.head()

  listingid     saleprice    datesold  daysonmarket
0    L01179  9.255800e+05  2023-07-07     65.005560
1    L00866  1.054160e+05  2023-06-14     38.004620
2    L00102  1.825184e+06  2023-09-09     22.992622
3    L00440  1.932085e+06  2023-10-29     72.012274
4    L00059  7.765860e+05  2023-05-01    116.000152

In [13]:
property_df = pd.read_json("/Users/mukundanramesh/projects/guvi-python-sql-pandas-project-1/datasets/property_attributes_final_expanded.json")
property_df.rename(columns={
    "attribute_id":"attributeid",
    "listing_id":"listingid",
    "floor_number":"floornumber",
    "total_floors":"totalfloors",
    "year_built":"yearbuilt",
    "is_rented":"isrented",
    "tenant_count":"tenantcount",
    "furnishing_status":"furnishingstatus",
    "metro_distance_km":"metrodistancekm",
    "parking_available":"parkingavailable",
    "power_backup":"powerbackup"
}, inplace=True)
property_df.head()

,attributeid,listingid,bedrooms,bathrooms,floornumber,totalfloors,yearbuilt,isrented,tenantcount,furnishingstatus,metrodistancekm,parkingavailable,powerbackup
0,1,L00001,5,3,9,9,2001,True,4,Furnished,7.26,False,True
1,2,L00002,2,2,19,29,2020,False,0,Unfurnished,4.84,True,False
2,3,L00003,2,3,8,26,2007,True,4,Semi-Furnished,4.92,False,False
3,4,L00004,3,3,25,10,2003,False,3,Furnished,1.20,False,True
4,5,L00005,2,2,15,16,2008,True,1,Semi-Furnished,7.90,False,False

In [14]:
display(agents_df.info())
display(buyers_df.info())
display(listings_df.info())
display(property_df.info())
display(sales_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   agentid          50 non-null     object
 1   name             50 non-null     object
 2   phone            50 non-null     object
 3   email            50 non-null     object
 4   commissionrate   50 non-null     float64
 5   dealsclosed      50 non-null     int64
 6   rating           50 non-null     float64
 7   experienceyears  50 non-null     int64
 8   avgclosingdays   50 non-null     int64
dtypes: float64(2), int64(3), object(4)
memory usage: 3.6+ KB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   buyerid       20000 non-null  int64
 1   saleid        20000 non-null  object
 2   buyertype     20000 non-null  object
 3   paymentmode   20000 non-null  object
 4   loantaken     20000 non-null  bool
 5   loanprovider  10034 non-null  object
 6   loanamount    20000 non-null  int64
dtypes: bool(1), int64(2), object(4)
memory usage: 957.2+ KB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21200 entries, 0 to 21199
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   listingid     21200 non-null  object
 1   city          21200 non-null  object
 2   propertytype  21200 non-null  object
 3   price         21200 non-null  float64
 4   sqft          21200 non-null  float64
 5   datelisted    21200 non-null  object
 6   agentid       21200 non-null  object
 7   latitude      21200 non-null  float64
 8   longitude     21200 non-null  float64
dtypes: float64(4), object(5)
memory usage: 1.5+ MB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21200 entries, 0 to 21199
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   attributeid       21200 non-null  int64
 1   listingid         21200 non-null  object
 2   bedrooms          21200 non-null  int64
 3   bathrooms         21200 non-null  int64
 4   floornumber       21200 non-null  int64
 5   totalfloors       21200 non-null  int64
 6   yearbuilt         21200 non-null  int64
 7   isrented          21200 non-null  bool
 8   tenantcount       21200 non-null  int64
 9   furnishingstatus  21200 non-null  object
 10  metrodistancekm   21200 non-null  float64
 11  parkingavailable  21200 non-null  bool
 12  powerbackup       21200 non-null  bool
dtypes: bool(3), float64(1), int64(7), object(2)
memory usage: 1.7+ MB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   listingid     720 non-null    object
 1   saleprice     720 non-null    float64
 2   datesold      720 non-null    object
 3   daysonmarket  720 non-null    float64
dtypes: float64(2), object(2)
memory usage: 22.6+ KB

None

# Database design

In [15]:
conn = sqlite3.connect("project.db")
cursor = conn.cursor()
conn.execute("PRAGMA foreign_keys = ON;")

In [26]:
#Query to create the agents table
agents_table_query = """
CREATE TABLE agents(
    agentid TEXT PRIMARY KEY,
    name TEXT,
    phone TEXT,
    email TEXT,
    commissionrate REAL,
    dealsclosed INTEGER,
    rating REAL,
    experienceyears INTEGER,
    avgclosingdays INTEGER
);
"""
cursor.execute(agents_table_query)
agents_df.to_sql("agents", conn, if_exists="append", index=False)
conn.commit()

In [21]:
agents_select_query = "select * from agents limit 1;"
result = pd.read_sql(agents_select_query, conn)
print(result)

  agentid         name            phone                 email  commissionrate  \
0   A0001  Agent A0001  +1-534-665-8373  a0001@realestate.com             2.0

   dealsclosed  rating  experienceyears  avgclosingdays
0           52     4.3               10              64

In [27]:
#Query to create the lisiting table
listings_table_query = """
CREATE TABLE listings(
    listingid TEXT PRIMARY KEY,
    city TEXT,
    propertytype TEXT,
    price REAL,
    sqft REAL,
    datelisted DATE,
    agentid TEXT,
    latitude REAL,
    longitude REAL,

    FOREIGN KEY(agentid)
        REFERENCES agents(agentid)
);
"""
cursor.execute(listings_table_query)
listings_df.to_sql("listings", conn, if_exists="append", index=False)
conn.commit()

In [31]:
listings_select_query = "select * from listings limit 1;"
result = pd.read_sql(listings_select_query, conn)
print(result)

  listingid      city propertytype         price         sqft  datelisted  \
0    L00001  New York    Apartment  1.655144e+06  2753.009121  2023-05-06

  agentid   latitude  longitude
0   A0015  33.965208 -69.861589

In [28]:
#Query to create the sales table
sales_table_query = """
CREATE TABLE sales(
    listingid TEXT PRIMARY KEY,
    saleprice REAL,
    datesold DATE,
    daysonmarket INTEGER,

    FOREIGN KEY(listingid)
        REFERENCES listings(listingid)
);
"""
cursor.execute(sales_table_query)
sales_df.to_sql("sales", conn, if_exists="append", index=False)
conn.commit()

In [ ]:
sales_select_query = "select * from sales limit 1;"
result = pd.read_sql(sales_select_query, conn)
print(result)

  listingid      saleprice    datesold  daysonmarket
0    L01179  925580.004193  2023-07-07      65.00556

In [29]:
#Query to create the buyers table
buyers_table_query = """
CREATE TABLE buyers(
    buyerid INTEGER PRIMARY KEY,
    saleid TEXT,

    buyertype TEXT,
    paymentmode TEXT,
    loantaken BOOLEAN,
    loanprovider TEXT,
    loanamount REAL,

    FOREIGN KEY(saleid)
        REFERENCES sales(listingid)
);
"""
cursor.execute(buyers_table_query)
buyers_df.to_sql("buyers", conn, if_exists="append", index=False)
conn.commit()

In [ ]:
buyers_select_query = "select * from buyers limit 1;"
result = pd.read_sql(buyers_select_query, conn)
print(result)

   buyerid  saleid buyertype paymentmode  loantaken loanprovider  loanamount
0        1  L01179  End User        Cash          0         None         0.0

In [30]:
property_attributes_table_query = """
CREATE TABLE property_attributes(
    attributeid INTEGER PRIMARY KEY,
    listingid TEXT,
    bedrooms INTEGER,
    bathrooms INTEGER,
    floornumber INTEGER,
    totalfloors INTEGER,
    yearbuilt INTEGER,
    isrented BOOLEAN,
    tenantcount INTEGER,
    furnishingstatus TEXT,
    metrodistancekm REAL,
    parkingavailable BOOLEAN,
    powerbackup BOOLEAN,

    FOREIGN KEY(listingid)
        REFERENCES listings(listingid)
);
"""
cursor.execute(property_attributes_table_query)
property_df.to_sql("property_attributes", conn, if_exists="append", index=False)
conn.commit()

In [ ]:
property_select_query = "select * from property_attributes limit 1;"
result = pd.read_sql(property_select_query, conn)
print(result)

   attributeid listingid  bedrooms  bathrooms  floornumber  totalfloors  \
0            1    L00001         5          3            9            9

   yearbuilt  isrented  tenantcount furnishingstatus  metrodistancekm  \
0       2001         1            4        Furnished             7.26

   parkingavailable  powerbackup
0                 0            1

In [32]:
# Agents
cursor.execute("""
CREATE INDEX IF NOT EXISTS idx_agents_rating
ON agents(rating);
""")

cursor.execute("""
CREATE INDEX IF NOT EXISTS idx_agents_experience
ON agents(experienceyears);
""")

# Listings
cursor.execute("""
CREATE INDEX IF NOT EXISTS idx_listings_city
ON listings(city);
""")

cursor.execute("""
CREATE INDEX IF NOT EXISTS idx_listings_propertytype
ON listings(propertytype);
""")

cursor.execute("""
CREATE INDEX IF NOT EXISTS idx_listings_price
ON listings(price);
""")

cursor.execute("""
CREATE INDEX IF NOT EXISTS idx_listings_agentid
ON listings(agentid);
""")

# Sales
cursor.execute("""
CREATE INDEX IF NOT EXISTS idx_sales_datesold
ON sales(datesold);
""")

cursor.execute("""
CREATE INDEX IF NOT EXISTS idx_sales_saleprice
ON sales(saleprice);
""")

# Buyers
cursor.execute("""
CREATE INDEX IF NOT EXISTS idx_buyers_saleid
ON buyers(saleid);
""")

cursor.execute("""
CREATE INDEX IF NOT EXISTS idx_buyers_buyertype
ON buyers(buyertype);
""")

cursor.execute("""
CREATE INDEX IF NOT EXISTS idx_buyers_paymentmode
ON buyers(paymentmode);
""")

# Property Attributes
cursor.execute("""
CREATE INDEX IF NOT EXISTS idx_property_bedrooms
ON property_attributes(bedrooms);
""")

cursor.execute("""
CREATE INDEX IF NOT EXISTS idx_property_yearbuilt
ON property_attributes(yearbuilt);
""")

cursor.execute("""
CREATE INDEX IF NOT EXISTS idx_property_metrodistance
ON property_attributes(metrodistancekm);
""")

cursor.execute("""
CREATE INDEX IF NOT EXISTS idx_property_listingid
ON property_attributes(listingid);
""")

conn.commit()

print("All indexes created successfully.")

All indexes created successfully.

# SQL analysis

### 1. What is the average listing price by city?

In [36]:
query1 = "select city, avg(price) as 'average listing price' from listings group by city;"
result = pd.read_sql(query1, conn)
result

          city  average listing price
0      Chicago           2.430678e+06
1      Houston           2.436811e+06
2  Los Angeles           2.442418e+06
3     New York           2.493320e+06
4      Phoenix           2.459962e+06